import { useEffect, useMemo, useRef, useState } from 'react'
import './App.css'

type RouteOption = {
  provider: string
  rail: string
  rate: string
  fee: string
  recipientAmount: string
  speed: string
  kyc: string
  confidence: string
  recommended?: boolean
}

type KycStep = {
  partner: string
  requirement: string
  source: string
  status: string
}

type TimelineItem =
  | { type: 'command'; text: string }
  | { type: 'log'; label: string; text: string }
  | { type: 'routes'; label: string }
  | { type: 'kyc'; label: string }
  | { type: 'payment'; label: string }
  | { type: 'complete'; label: string; text: string }

const routeOptions: RouteOption[] = [
  {
    provider: 'Global bank wire',
    rail: 'Correspondent bank',
    rate: '1 USD = 7.04 CNY (wide spread)',
    fee: '$32.00',
    recipientAmount: '6,815.04 CNY',
    speed: '2-4 business days',
    kyc: 'Low',
    confidence: '92%',
  },
  {
    provider: 'Wise',
    rail: 'Local payout network',
    rate: '1 USD = 7.12 CNY',
    fee: '$8.10',
    recipientAmount: '7,059.35 CNY',
    speed: 'Same day',
    kyc: 'Medium',
    confidence: '95%',
  },
  {
    provider: 'Card remittance',
    rail: 'Card funding + local payout',
    rate: '1 USD = 7.09 CNY',
    fee: '$19.80',
    recipientAmount: '6,949.82 CNY',
    speed: 'Minutes',
    kyc: 'Medium',
    confidence: '88%',
  },
  {
    provider: 'X stablecoin route',
    rail: 'ACH -> USDC -> CNY off-ramp',
    rate: '1 USD = 7.24 CNY (near spot)',
    fee: '$2.40',
    recipientAmount: '7,211.42 CNY',
    speed: '18 minutes',
    kyc: 'Reused + partner checks',
    confidence: '97%',
    recommended: true,
  },
]

const kycSteps: KycStep[] = [
  {
    partner: 'X secure vault',
    requirement: 'Stored PII profile',
    source: 'Legal name, address, DOB, ID metadata, Travel Rule fields',
    status: 'Retrieved with masked values',
  },
  {
    partner: 'US on-ramp partner',
    requirement: 'Regulated partner KYC',
    source: 'Submitted from encrypted profile',
    status: 'Approved',
  },
  {
    partner: 'CNY off-ramp partner',
    requirement: 'Recipient + Travel Rule check',
    source: 'Reused stored sender PII; added corridor metadata',
    status: 'Approved',
  },
  {
    partner: 'Compliance screen',
    requirement: 'Sanctions, velocity, corridor risk',
    source: 'Route evidence packet generated by agent',
    status: 'Cleared',
  },
]

const paymentFacts = [
  ['Funding method', 'Tokenized ACH account ending 4821'],
  ['Amount pulled', '$1,000.00 USD'],
  ['Route', 'ACH -> USDC liquidity -> CNY off-ramp'],
  ['Expected arrival', '18 minutes'],
  ['User action', 'No form refill; saved payment method reused'],
]

const timeline: TimelineItem[] = [
  {
    type: 'command',
    text: 'Using X, do a cross-border remittance from USD to Chinese yuan.',
  },
  {
    type: 'log',
    label: 'intent.parsed',
    text: 'Send 1,000 USD to CNY. Returning user profile detected.',
  },
  {
    type: 'log',
    label: 'market.scan',
    text: 'Comparing bank wire, Wise, card-funded remittance, and stablecoin settlement.',
  },
  { type: 'routes', label: 'routes.compared' },
  {
    type: 'log',
    label: 'route.selected',
    text: 'Stablecoin route wins on net recipient amount and settlement speed.',
  },
  {
    type: 'log',
    label: 'vault.opened',
    text: 'Secure PII vault unlocked for regulated partner submissions. Sensitive values remain masked.',
  },
  { type: 'kyc', label: 'kyc.automated' },
  {
    type: 'log',
    label: 'evidence.resolved',
    text: 'Agent answered provider evidence requests with stored documents and corridor metadata.',
  },
  { type: 'payment', label: 'payment.prepared' },
  {
    type: 'log',
    label: 'payment.confirmed',
    text: 'ACH authorization accepted with tokenized payment method. No new payment details required.',
  },
  {
    type: 'complete',
    label: 'transfer.complete',
    text: '$1,000 USD sent. 7,211.42 CNY delivered to destination account.',
  },
]

const STEP_DELAY_MS = 15_000

function App() {
  const stepDelayMs =
    new URLSearchParams(window.location.search).get('speed') === 'fast'
      ? 700
      : STEP_DELAY_MS
  const [visibleCount, setVisibleCount] = useState(1)
  const [runId, setRunId] = useState(1)
  const [notificationOpen, setNotificationOpen] = useState(false)
  const [notificationDismissed, setNotificationDismissed] = useState(false)
  const terminalEndRef = useRef<HTMLDivElement | null>(null)
  const visibleTimeline = useMemo(
    () => timeline.slice(0, visibleCount),
    [visibleCount],
  )
  const isComplete = visibleCount >= timeline.length

  useEffect(() => {
    if (visibleCount >= timeline.length) {
      return
    }

    const timeout = window.setTimeout(() => {
      setVisibleCount((count) => Math.min(count + 1, timeline.length))
    }, stepDelayMs)

    return () => window.clearTimeout(timeout)
  }, [stepDelayMs, visibleCount])

  useEffect(() => {
    terminalEndRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' })
  }, [visibleTimeline])

  useEffect(() => {
    if (isComplete && !notificationDismissed) {
      setNotificationOpen(true)
    }
  }, [isComplete, notificationDismissed, runId])

  const restartFlow = () => {
    setVisibleCount(1)
    setNotificationOpen(false)
    setNotificationDismissed(false)
    setRunId((currentRunId) => currentRunId + 1)
  }

  const closeNotification = () => {
    setNotificationOpen(false)
    setNotificationDismissed(true)
  }

  return (
    <main className="demo-page">
      <section className="terminal-stage" aria-label="X cross-border demo">
        <div className="brand-strip">
          <div>
            <p className="eyebrow">X agent terminal</p>
            <h1>USD to CNY remittance run</h1>
          </div>
          <button className="rerun-button" type="button" onClick={restartFlow}>
            Rerun flow
          </button>
        </div>

        <div className="terminal-window">
          <div className="terminal-header">
            <div className="window-controls" aria-hidden="true">
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div className="terminal-title">x-remit --corridor USD/CNY</div>
            <div className="terminal-status">live simulation</div>
          </div>

          <div className="terminal-body" aria-live="polite">
            {visibleTimeline.map((item, index) => (
              <TerminalItem item={item} key={`${item.type}-${index}`} />
            ))}
            {!isComplete && (
              <div className="terminal-line active-line">
                <span className="line-label">agent.running</span>
                <span className="typing-dots" aria-label="Agent is working">
                  <i></i>
                  <i></i>
                  <i></i>
                </span>
              </div>
            )}
            <div ref={terminalEndRef} />
          </div>
        </div>
      </section>

      <aside
        className={`mac-notification ${notificationOpen ? 'is-visible' : ''}`}
        aria-hidden={!notificationOpen}
      >
        <div className="wechat-mark" aria-label="WeChat">
          <svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
            <circle cx="15" cy="19" r="10" fill="#fff" />
            <circle cx="26" cy="15" r="11" fill="#fff" fillOpacity="0.88" />
          </svg>
        </div>
        <div>
          <div className="notification-topline">
            <strong>WeChat</strong>
            <span>now</span>
          </div>
          <p>X delivered 7,211.42 CNY to your WeChat Wallet balance.</p>
        </div>
        <button
          className="notification-close"
          type="button"
          aria-label="Close funds arrival notification"
          onClick={closeNotification}
        >
          ×
        </button>
      </aside>
    </main>
  )
}

function TerminalItem({ item }: { item: TimelineItem }) {
  if (item.type === 'command') {
    return (
      <div className="terminal-line command-line">
        <span className="prompt-symbol">$</span>
        <span>{item.text}</span>
      </div>
    )
  }

  if (item.type === 'routes') {
    return (
      <section className="terminal-panel">
        <PanelHeader label={item.label} title="Provider route comparison" />
        <div className="route-table">
          {routeOptions.map((route) => (
            <article
              className={`route-row ${route.recommended ? 'is-winner' : ''}`}
              key={route.provider}
            >
              <div>
                <strong>{route.provider}</strong>
                <span>{route.rail}</span>
              </div>
              <div>{route.rate}</div>
              <div>{route.fee}</div>
              <div>{route.recipientAmount}</div>
              <div>{route.speed}</div>
              <div>
                <span className="status-pill">{route.confidence}</span>
              </div>
            </article>
          ))}
        </div>
        <p className="panel-note">
          Recommendation: X stablecoin route hits the tightest CNY quote (near
          onshore spot) with the lowest all-in fee and fastest settlement while
          preserving regulated partner checks.
        </p>
      </section>
    )
  }

  if (item.type === 'kyc') {
    return (
      <section className="terminal-panel">
        <PanelHeader label={item.label} title="KYC reuse and partner checks" />
        <div className="secure-vault">
          <div>
            <span className="vault-label">Encrypted PII vault</span>
            <strong>Returning user profile found</strong>
            <p>Jane D*** | DOB **/**/1990 | ID ****-4829 | 221B M***** St</p>
          </div>
          <span className="status-pill secure">masked + tokenized</span>
        </div>
        <div className="kyc-grid">
          {kycSteps.map((step) => (
            <article className="kyc-card" key={step.partner}>
              <span>{step.partner}</span>
              <strong>{step.requirement}</strong>
              <p>{step.source}</p>
              <em>{step.status}</em>
            </article>
          ))}
        </div>
      </section>
    )
  }

  if (item.type === 'payment') {
    return (
      <section className="terminal-panel payment-panel">
        <PanelHeader label={item.label} title="ACH payment prepared" />
        <div className="payment-grid">
          {paymentFacts.map(([label, value]) => (
            <div key={label}>
              <span>{label}</span>
              <strong>{value}</strong>
            </div>
          ))}
        </div>
        <div className="authorization-card">
          <span>ACH mandate</span>
          <strong>Authorized from saved token</strong>
          <p>Repeat transfers can reuse this method without refilling bank details.</p>
        </div>
      </section>
    )
  }

  if (item.type === 'complete') {
    return (
      <div className="terminal-line success-line">
        <span className="line-label">{item.label}</span>
        <span>{item.text}</span>
      </div>
    )
  }

  return (
    <div className="terminal-line">
      <span className="line-label">{item.label}</span>
      <span>{item.text}</span>
    </div>
  )
}

function PanelHeader({ label, title }: { label: string; title: string }) {
  return (
    <div className="panel-header">
      <span className="line-label">{label}</span>
      <strong>{title}</strong>
    </div>
  )
}

export default App
